[package]
name = "minigrep"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
colored = "3.0.0"
regex = "1.11.1"
num_cpus = "1.0"

walkdir = "2.5.0"
